const menuData = [
    { name: 'CHICKEN 65', price: 9.99, category: 'Non Veg Starters', description: 'Spice Level: 2', image: '/chicken-65.webp' },
    { name: 'CHILLI CHICKEN', price: 9.99, category: 'Non Veg Starters', description: 'Spice Level: 3', image: '/chilli-chicken.webp' },
    { name: 'CHICKEN MAJESTIC', price: 11.99, category: 'Non Veg Starters', description: 'Spice Level: 2', image: '/majestic-chicken.webp' },
    { name: 'CHICKEN TIKKA KEBAB (4 PCS)', price: 11.99, category: 'Non Veg Starters', description: 'Spice Level: 2', image: '/chicken-tikka-kebab.webp' },
    { name: 'CHICKEN SEEKH KEBAB (4 PCS)', price: 10.99, category: 'Non Veg Starters', description: 'Spice Level: 2', image: '/chicken-seekh-kebab.webp' },
    { name: 'PEPPER CHICKEN', price: 11.99, category: 'Non Veg Starters', description: 'Spice Level: 3' },
    { name: 'CHICKEN TANDOORI FULL', price: 14.99, category: 'Non Veg Starters', description: 'Spice Level: 2', image: '/chicken-tandoori-full.webp' },
    { name: 'CHICKEN TANDOORI HALF', price: 9.99, category: 'Non Veg Starters', description: 'Spice Level: 2', image: '/chicken-tandoori-half.webp' },
    { name: 'CHICKEN TANGDI (4 PCS)', price: 9.99, category: 'Non Veg Starters', description: 'Spice Level: 2', image: '/chicken-tangdi.webp' },
    { name: 'LAMB SEEKH KEBAB (4 PCS)', price: 11.99, category: 'Non Veg Starters', description: 'Spice Level: 2', image: '/lamb-seekh-kebab.webp' },
    { name: 'LAMB CHOPS (4 PCS)', price: 12.99, category: 'Non Veg Starters', description: 'Spice Level: 2', image: '/lamb-chops.webp' },
    { name: 'MUTTON HALEEM', price: 14.99, category: 'Non Veg Starters', description: 'Spice Level: 1', image: '/mutton-haleem.webp' },
    { name: 'MUTTON MARAG', price: 14.99, category: 'Non Veg Starters', description: 'Spice Level: 1' },
    { name: 'MASALA FISH (1 PC)', price: 7.99, category: 'Sea Food', description: 'Spice Level: 2', image: '/masala-fish.webp' },
    { name: 'APOLLO FISH', price: 14.99, category: 'Sea Food', description: 'Spice Level: 2' },
    { name: 'TANDOORI GRILLED FISH', price: 14.99, category: 'Sea Food', description: 'Spice Level: 2', image: '/tandoori-grill-fish.webp' },
    { name: 'CHILLI GARLIC PRAWNS', price: 14.99, category: 'Sea Food', description: 'Spice Level: 3' },
    { name: 'VEG SPRING ROLL (6 PCS)', price: 7.99, category: 'Veg Starters', description: 'Spice Level: 1' },
    { name: 'TANDOORI PANEER TIKKA', price: 10.99, category: 'Veg Starters', description: 'Spice Level: 2' },
    { name: 'VEG DUM BIRYANI (SINGLE)', price: 7.99, category: 'Biryani', description: 'Spice Level: 2' },
    { name: 'CHICKEN BIRYANI (SINGLE)', price: 8.99, category: 'Biryani', description: 'Spice Level: 2' },
    { name: 'CHICKEN BIRYANI (DOUBLE)', price: 16.99, category: 'Biryani', description: 'Spice Level: 2' },
    { name: 'CHICKEN BIRYANI (FAMILY)', price: 22.99, category: 'Biryani', description: 'Spice Level: 2' },
    { name: 'CHICKEN BIRYANI (JUMBO)', price: 29.99, category: 'Biryani', description: 'Spice Level: 2' },
    { name: 'LAMB BIRYANI (SINGLE)', price: 11.99, category: 'Biryani', description: 'Spice Level: 2' },
    { name: 'LAMB BIRYANI (DOUBLE)', price: 19.99, category: 'Biryani', description: 'Spice Level: 2' },
    { name: 'LAMB BIRYANI (FAMILY)', price: 29.99, category: 'Biryani', description: 'Spice Level: 2' },
    { name: 'LAMB BIRYANI (JUMBO)', price: 39.99, category: 'Biryani', description: 'Spice Level: 2' },
    { name: 'THAALI FOR 2 (LAMB)', price: 29.99, category: 'Biryani Thaali', description: '1 Double Biryani, Chicken 65, Chilli Chicken, 1 Pc Tandoori, 1 Naan, 1 Rumali, 2 Drinks', image: '/lamb-biryani-thaali-for-2-people.webp' },
    { name: 'THAALI FOR 2 (CHICKEN)', price: 25.99, category: 'Biryani Thaali', description: '1 Double Biryani, Chicken 65, Chilli Chicken, 1 Pc Tandoori, 1 Naan, 1 Rumali, 2 Drinks', image: '/chicken-biryani-thaali-for-2-people.webp' },
    { name: 'THAALI FOR 4 (LAMB)', price: 59.99, category: 'Biryani Thaali', description: '2 Double Biryani, 2 Pc Tandoori, 2 Naan, 2 Rumali, 4 Drinks', image: '/lamb-biryani-thaali-for-4-people.webp' },
    { name: 'THAALI FOR 4 (CHICKEN)', price: 54.99, category: 'Biryani Thaali', description: '2 Double Biryani, 2 Pc Tandoori, 2 Naan, 2 Rumali, 4 Drinks', image: '/chicken-biryani-thaali-for-4-people.webp' },
    { name: 'DUM KA CHICKEN', price: 12.99, category: 'Chicken Main Course', description: 'Spice Level: 2' },
    { name: 'BUTTER CHICKEN', price: 12.99, category: 'Chicken Main Course', description: 'Spice Level: 1' },
    { name: 'BHEJA FRY MASALA', price: 14.99, category: 'Mutton Main Course', description: 'Spice Level: 2' },
    { name: 'GURDA FRY MASALA', price: 14.99, category: 'Mutton Main Course', description: 'Spice Level: 2' },
    { name: 'KALEJI FRY MASALA', price: 14.99, category: 'Mutton Main Course', description: 'Spice Level: 2' },
    { name: 'TALAWA GOSHT', price: 16.99, category: 'Mutton Main Course', description: 'Spice Level: 2' },
    { name: 'MUTTON MASALA', price: 16.99, category: 'Mutton Main Course', description: 'Spice Level: 2' },
    { name: 'PLAIN RICE', price: 4.99, category: 'Rice', description: 'Fragrant basmati rice' },
    { name: 'ZEERA RICE', price: 5.99, category: 'Rice', description: 'Fragrant basmati rice' },
    { name: 'TADKA DAL', price: 9.99, category: 'Veg Main Course', description: 'Spice Level: 1' },
    { name: 'DAL FRY', price: 12.99, category: 'Veg Main Course', description: 'Spice Level: 1' },
    { name: 'SHAHI PANEER', price: 12.99, category: 'Veg Main Course', description: 'Spice Level: 1' },
    { name: 'PANEER BUTTER MASALA', price: 12.99, category: 'Veg Main Course', description: 'Spice Level: 1' },
    { name: 'CHICKEN MANDI (1 PERSON)', price: 11.99, category: 'Nizami Mandi', description: 'Spice Level: 1' },
    { name: 'CHICKEN MANDI (2 PERSONS)', price: 18.99, category: 'Nizami Mandi', description: 'Spice Level: 1' },
    { name: 'CHICKEN MANDI JUICY (1 PERSON)', price: 13.99, category: 'Nizami Mandi', description: 'Spice Level: 1' },
    { name: 'CHICKEN MANDI JUICY (2 PERSONS)', price: 20.99, category: 'Nizami Mandi', description: 'Spice Level: 1' },
    { name: 'LAMB MANDI (1 PERSON)', price: 13.99, category: 'Nizami Mandi', description: 'Spice Level: 1' },
    { name: 'LAMB MANDI (2 PERSONS)', price: 21.99, category: 'Nizami Mandi', description: 'Spice Level: 1' },
    { name: 'LAMB MANDI JUICY (1 PERSON)', price: 15.99, category: 'Nizami Mandi', description: 'Spice Level: 1' },
    { name: 'LAMB MANDI JUICY (2 PERSONS)', price: 23.99, category: 'Nizami Mandi', description: 'Spice Level: 1' },
    { name: 'CHICKEN 65 MANDI', price: 12.99, category: 'Nizami Mandi', description: 'Spice Level: 1' },
    { name: 'CHICKEN TIKKA MANDI', price: 12.99, category: 'Nizami Mandi', description: 'Spice Level: 1' },
    { name: 'FISH MANDI', price: 12.99, category: 'Nizami Mandi', description: 'Spice Level: 1' },
    { name: 'MINGLED MINI PLATTER (3 PERSONS)', price: 39.99, category: 'Mandi Platters', description: 'Lamb 1pc, Chicken Leg 1pc, Fish 1pc, Chicken 65' },
    { name: 'BLENDED PLATTER (5 PERSONS)', price: 64.99, category: 'Mandi Platters', description: 'Lamb 2pcs, Chicken Leg 2pcs, Fish 2pcs, Chicken Tikka 2pcs, Chicken 65, Lamb Chops 2pcs' },
    { name: 'JUMBLED PLATTER (7 PERSONS)', price: 84.99, category: 'Mandi Platters', description: 'Lamb 3pcs, Chicken Leg 3pcs, Fish 3pcs, Chicken Tikka 3pcs, Chicken 65, Lamb Chops 3pcs' },
    { name: 'NIZAMI\'S SPECIAL PLATTER', price: 119.00, category: 'Mandi Platters', description: 'Lamb 3pcs, Chicken Legs 3pcs, Fish 3pcs, Chicken Tikka 3pcs, Chicken 65, Lamb Chops 3pcs, Half Faham' },
    { name: 'SOUP', price: 2.49, category: "Extra's", description: 'Warm comforting soup' },
    { name: 'MANDI RICE', price: 6.99, category: "Extra's", description: 'Aromatic mandi rice' },
    { name: 'CHICKEN PIECE', price: 6.99, category: "Extra's", description: 'Extra chicken piece' },
    { name: 'CHICKEN TIKKA (2 PCS)', price: 6.99, category: "Extra's", description: 'Extra chicken tikka' },
    { name: 'CHICKEN 65', price: 6.99, category: "Extra's", description: 'Extra chicken 65' },
    { name: 'FISH PIECE', price: 7.99, category: "Extra's", description: 'Extra fish piece' },
    { name: 'LAMB PIECE', price: 8.99, category: "Extra's", description: 'Extra lamb piece' },
    { name: 'LAMB CHOPS (2 PCS)', price: 7.99, category: "Extra's", description: 'Extra lamb chops' },
    { name: 'MANDI SAUCE', price: 1.99, category: "Extra's", description: 'Authentic mandi sauce' },
    { name: 'MAYONNAISE', price: 2.49, category: "Extra's", description: 'Creamy mayonnaise' },
    { name: 'PLAIN NAAN / PLAIN ROTI', price: 1.99, category: 'Breads (Naan & Roti)', description: 'Freshly baked' },
    { name: 'BUTTER NAAN / BUTTER ROTI', price: 2.49, category: 'Breads (Naan & Roti)', description: 'Freshly baked with butter' },
    { name: 'GARLIC NAAN', price: 2.99, category: 'Breads (Naan & Roti)', description: 'Freshly baked with garlic' },
    { name: 'CHEESE NAAN', price: 2.99, category: 'Breads (Naan & Roti)', description: 'Freshly baked with cheese' },
    { name: 'CHILLI CHEESE NAAN', price: 2.99, category: 'Breads (Naan & Roti)', description: 'Freshly baked with chilli & cheese' },
    { name: 'CHILLI GARLIC NAAN', price: 3.49, category: 'Breads (Naan & Roti)', description: 'Freshly baked with chilli & garlic' },
    { name: 'CHEESE GARLIC NAAN', price: 3.49, category: 'Breads (Naan & Roti)', description: 'Freshly baked with cheese & garlic' },
    { name: 'KEEMA NAAN', price: 3.49, category: 'Breads (Naan & Roti)', description: 'Freshly baked with minced meat' },
    { name: 'ICE CREAM (2 SCOOPS)', price: 4.99, category: 'Desserts', description: 'Refreshing ice cream' },
    { name: 'GULAB JAMUN (2 PCS)', price: 4.99, category: 'Desserts', description: 'Warm syrupy dumplings' },
    { name: 'SHAHI TUKDA (4 PCS)', price: 5.99, category: 'Desserts', description: 'Royal bread pudding' },
    { name: 'QUBANI KA MEETHA', price: 6.99, category: 'Desserts', description: 'Traditional apricot dessert' },
    { name: 'QUBANI KA MEETHA WITH ICE CREAM', price: 8.99, category: 'Desserts', description: 'Traditional apricot dessert with ice cream' },
    { name: 'GAJAR KA HALWA', price: 7.99, category: 'Desserts', description: 'Sweet carrot pudding' },
    { name: 'SUNRISE DELIGHT (REGULAR)', price: 8.99, category: 'Desserts', description: 'Nizam special delight' },
    { name: 'SUNRISE DELIGHT (LARGE)', price: 18.99, category: 'Desserts', description: 'Nizam special delight family size' },
    { name: 'SWEET LASSI (GLASS)', price: 4.99, category: 'Lassi', description: 'Refreshing sweet lassi' },
    { name: 'SWEET LASSI (JUG)', price: 12.99, category: 'Lassi', description: 'Refreshing sweet lassi jug' },
    { name: 'SALT LASSI (GLASS)', price: 4.99, category: 'Lassi', description: 'Refreshing salt lassi' },
    { name: 'SALT LASSI (JUG)', price: 12.99, category: 'Lassi', description: 'Refreshing salt lassi jug' },
    { name: 'MANGO LASSI (GLASS)', price: 5.99, category: 'Lassi', description: 'Refreshing mango lassi' },
    { name: 'MANGO LASSI (JUG)', price: 14.99, category: 'Lassi', description: 'Refreshing mango lassi jug' },
    { name: 'MANGO MILK SHAKE', price: 7.99, category: 'Milk Shakes', description: 'Indulgent mango shake' },
    { name: 'OREO BISCUIT MILK SHAKE', price: 7.99, category: 'Milk Shakes', description: 'Indulgent oreo shake' },
    { name: 'FERRERO MILK SHAKE', price: 8.99, category: 'Milk Shakes', description: 'Indulgent ferrero shake' },
    { name: 'KITKAT MILK SHAKE', price: 8.99, category: 'Milk Shakes', description: 'Indulgent kitkat shake' },
    { name: 'CHOCOLATE MILK SHAKE', price: 8.99, category: 'Milk Shakes', description: 'Indulgent chocolate shake' },
    { name: 'VIRGIN MOJITO', price: 6.99, category: 'Mock Tails', description: 'Refreshing mojito' },
    { name: 'BLUE LAGOON', price: 6.99, category: 'Mock Tails', description: 'Refreshing blue lagoon' },
    { name: 'PINA COLADA', price: 7.99, category: 'Mock Tails', description: 'Refreshing pina colada' },
    { name: 'FRUIT PUNCH', price: 7.99, category: 'Mock Tails', description: 'Refreshing fruit punch' },
    { name: 'SOFT DRINKS', price: 1.49, category: 'Drinks', description: 'Coke, Diet Coke, Pepsi, Diet Pepsi, 7Up, Mirinda, Tango' },
    { name: 'THUMS UP / JEERA SODA / RED BULL', price: 2.49, category: 'Drinks', description: 'Indian sodas & energy drinks' },
    { name: 'WATER BOTTLE', price: 1.00, category: 'Drinks', description: 'Mineral water' }
];

module.exports = { menuData };
